#!/usr/bin/env node

"use strict";

const simpleGit = require("simple-git");
const fs = require("fs/promises");

const git = simpleGit();
const commitMessageFileName = process.argv[2];

let messageUpdated = false;
let messageContainsTopic = false;

Promise.all([
  git.revparse(["--abbrev-ref", "HEAD"]),
  fs.readFile(commitMessageFileName),
])
  .then((results) => {
    let currentBranchName = results[0];
    let commitMessage = results[1].toString();
    let topic;
    let type;
    let matchCurrentBranch = currentBranchName.match(
      /^(feature|fix|internal)\/[^\/]+\/([^\/]+)/
    );

    if (matchCurrentBranch && !commitMessage.match(/^\[/)) {
      topic = matchCurrentBranch[2].trim();
      type = matchCurrentBranch[1].trim();
      type = type.toUpperCase();

      commitMessage = `[${type}] ${commitMessage}\n\n\nTopic: ${topic}`;
      messageUpdated = true;
    } else if (commitMessage.match(/^\[/)) {
      messageContainsTopic = true;
    }

    return fs.writeFile(commitMessageFileName, commitMessage);
  })
  .then(() => {
    if (messageUpdated) {
      console.info("Add topic info to commit message.");
    } else if (!messageContainsTopic) {
      console.warn(`Can not determin topic and type info from branch.\n\n
Name of branches to take topic and type: branch names:
feature/master/FXUBRQ21-1234/Tree_context_menu"
fix/s4ce-2105/FXUBRQ21-1234/Fix_bad_issue_for_current_cloud_release"
fix/s4op-2020sp0/FXUBRQ21-1234/Fix_bad_issue_for_current_onpremise_release"`);
    }
  })
  .catch((err) => {
    console.error(err);
  });
